name: Dataform CI/CD

on: 
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  dataform_unit_test:
    runs-on: ubuntu-latest
    name: Basic CI/CD Pipeline
    steps:
      - uses: actions/checkout@v2
      - name: Build Dataform Docker Image
        id: docker-build
        run: docker build . --file Dockerfile --tag my-unit-test-image:$(date +%s)
      - name: Run Unit Tests
        id: unit-test
        run: docker run my-unit-test-image:$(date +%s)