name: Dataform CI/CD

on: 
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  dataform_unit_test:
    runs-on: ubuntu-latest
    name: Basic CI/CD Pipeline
    steps:
      - uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}'
      
      - name: Login to GCP_CREDENTIALS
        run: gcloud auth application-default login 

      - name: Build Dataform Docker Image
        id: docker-build
        run: docker build . --file Dockerfile --tag my-unit-test-image:latest
      - name: Dataform Compile
        id: dataform-compile
        run: docker run my-unit-test-image:latest compile --timeout=10s
      - name: Dataform Run Unit Tests
        id: dataform-unit-test
        run: docker run my-unit-test-image:latest test --timeout=10s